/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountCreation: typeof import('./components/AccountCreation.vue')['default']
    AccountCredentials: typeof import('./components/accounts/accountCredentials.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Comments: typeof import('./components/Comments.vue')['default']
    EventDisplay: typeof import('./components/EventDisplay.vue')['default']
    EventList: typeof import('./components/EventList.vue')['default']
    Events: typeof import('./components/events.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MapComponent: typeof import('./components/MapComponent.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NewUserValidation: typeof import('./components/accounts/newUserValidation.vue')['default']
    PasswordPrompt: typeof import('./components/PasswordPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TermsOfService: typeof import('./components/TermsOfService.vue')['default']
  }
}
